"""
Odoo Café POS - Smart Restaurant Management System
Main Flask Application
"""

from flask import Flask, render_template, request, jsonify, session, redirect, url_for
from functools import wraps
from datetime import datetime, timedelta
import random
import string
import os

from models import (
    db, User, Customer, Category, Product, Floor, Table,
    Coupon, Promotion, Order, OrderItem, Payment, PointsLedger,
    POINTS_EARN_RATE, POINTS_REDEEM_VALUE
)

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
DB_PATH = os.path.join(BASE_DIR, 'database.db')

# Every coupon automatically expires this many days after it is created.
COUPON_VALIDITY_DAYS = 5


app = Flask(__name__)
app.config['SECRET_KEY'] = 'odoo-cafe-pos-secret-key-change-in-production'
app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_PATH}'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)


# ---------------------------------------------------------------------------
# Helpers / Decorators
# ---------------------------------------------------------------------------

def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if 'user_id' not in session:
            return jsonify({'error': 'Authentication required'}), 401
        return f(*args, **kwargs)
    return decorated


def role_required(*roles):
    def wrapper(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            if 'user_id' not in session:
                return jsonify({'error': 'Authentication required'}), 401
            if session.get('role') not in roles:
                return jsonify({'error': 'Insufficient permissions'}), 403
            return f(*args, **kwargs)
        return decorated
    return wrapper


def generate_order_number():
    return 'ORD-' + datetime.utcnow().strftime('%y%m%d') + '-' + ''.join(random.choices(string.digits, k=4))


def generate_qr_payload(text):
    """Returns a URL to a QR code image generated by an external free API (no API key)."""
    import urllib.parse
    encoded = urllib.parse.quote(text)
    return f"https://api.qrserver.com/v1/create-qr-code/?size=220x220&data={encoded}"


def get_or_create_customer_for_user(user):
    """Finds (or creates) the Customer record linked to a logged-in 'customer' role User,
    matched by email. This bridges the User auth table with the Customer CRM table so
    orders placed from the customer dashboard can be tied back to that person's history."""
    customer = Customer.query.filter_by(email=user.email).first()
    if not customer:
        customer = Customer(name=user.name, email=user.email)
        db.session.add(customer)
        db.session.flush()
    return customer


def recalc_order_totals(order, discount_value=0.0, discount_type='fixed'):
    subtotal = sum(item.price * item.quantity for item in order.items)
    tax_amount = sum((item.price * item.quantity) * (item.tax / 100.0) for item in order.items)

    if discount_type == 'percentage':
        discount = subtotal * (discount_value / 100.0)
    else:
        discount = discount_value

    grand_total = max(subtotal + tax_amount - discount, 0)
    order.subtotal = round(subtotal, 2)
    order.tax_amount = round(tax_amount, 2)
    order.discount = round(discount, 2)
    order.grand_total = round(grand_total, 2)


def points_value(points):
    """₹ value of a number of loyalty points."""
    return round(points * POINTS_REDEEM_VALUE, 2)


def apply_points_redemption(order, customer, requested_points=None):
    """Auto-applies a customer's available loyalty points as an extra discount on
    top of subtotal+tax-discount, capped so the order total never goes below 0 and
    never redeems more points than the customer actually has. Deducts the points
    from the customer's balance and writes a ledger entry, but does not commit —
    caller is expected to commit alongside the rest of the order changes.
    Returns (points_redeemed, points_discount_value)."""
    if not customer or customer.loyalty_points <= 0:
        return 0, 0.0

    available_points = customer.loyalty_points
    if requested_points is not None:
        available_points = min(available_points, max(0, int(requested_points)))

    # Don't let points discount drive the total below zero.
    remaining_payable = max(order.subtotal + order.tax_amount - order.discount, 0)
    max_points_usable = int(remaining_payable / POINTS_REDEEM_VALUE)
    points_to_redeem = min(available_points, max_points_usable)

    if points_to_redeem <= 0:
        return 0, 0.0

    discount_from_points = points_value(points_to_redeem)
    order.points_redeemed = points_to_redeem
    order.points_discount = discount_from_points
    order.discount = round(order.discount + discount_from_points, 2)
    order.grand_total = max(round(order.subtotal + order.tax_amount - order.discount, 2), 0)

    customer.loyalty_points -= points_to_redeem
    db.session.add(PointsLedger(
        customer_id=customer.id, order_id=order.id,
        change=-points_to_redeem, reason='redeemed',
        balance_after=customer.loyalty_points
    ))
    return points_to_redeem, discount_from_points


def award_points_for_order(order, customer):
    """Credits loyalty points for a paid order (1 point per ₹{POINTS_EARN_RATE} spent
    on the final grand_total). Writes a ledger entry. Does not commit."""
    if not customer:
        return 0
    earned = int(order.grand_total // POINTS_EARN_RATE)
    if earned <= 0:
        order.points_earned = 0
        return 0
    customer.loyalty_points += earned
    order.points_earned = earned
    db.session.add(PointsLedger(
        customer_id=customer.id, order_id=order.id,
        change=earned, reason='earned',
        balance_after=customer.loyalty_points
    ))
    return earned


# ---------------------------------------------------------------------------
# Page Routes (Frontend Views)
# ---------------------------------------------------------------------------

@app.route('/')
def index():
    return render_template('index.html')


@app.route('/login')
def login_page():
    return render_template('login.html')


@app.route('/dashboard')
def dashboard_page():
    if 'user_id' not in session or session.get('role') not in ('admin', 'employee'):
        return redirect(url_for('login_page'))
    return render_template('dashboard.html')


@app.route('/customer-dashboard')
def customer_dashboard_page():
    if 'user_id' not in session or session.get('role') != 'customer':
        return redirect(url_for('login_page'))
    return render_template('customer_dashboard.html')


@app.route('/pos')
def pos_page():
    if 'user_id' not in session or session.get('role') not in ('admin', 'employee'):
        return redirect(url_for('login_page'))
    return render_template('pos.html')


@app.route('/kitchen')
def kitchen_page():
    if 'user_id' not in session or session.get('role') not in ('admin', 'employee'):
        return redirect(url_for('login_page'))
    return render_template('kitchen.html')


@app.route('/self-order')
@app.route('/self-order/<int:table_id>')
def self_order_page(table_id=None):
    return render_template('self_order.html', table_id=table_id)


@app.route('/reports')
def reports_page():
    if 'user_id' not in session or session.get('role') != 'admin':
        return redirect(url_for('login_page'))
    return render_template('reports.html')


# ---------------------------------------------------------------------------
# Auth API
# ---------------------------------------------------------------------------

@app.route('/api/auth/register', methods=['POST'])
def register():
    data = request.get_json()
    name = data.get('name', '').strip()
    email = data.get('email', '').strip().lower()
    password = data.get('password', '')
    role = data.get('role', 'customer')

    if not name or not email or not password:
        return jsonify({'error': 'Name, email and password are required'}), 400

    if role not in ('admin', 'employee', 'customer'):
        role = 'customer'

    if User.query.filter_by(email=email).first():
        return jsonify({'error': 'Email already registered'}), 409

    user = User(name=name, email=email, role=role)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    return jsonify({'message': 'Registration successful', 'user': user.to_dict()}), 201


@app.route('/api/auth/login', methods=['POST'])
def login():
    data = request.get_json()
    email = data.get('email', '').strip().lower()
    password = data.get('password', '')

    user = User.query.filter_by(email=email).first()
    if not user or not user.check_password(password):
        return jsonify({'error': 'Invalid email or password'}), 401

    session['user_id'] = user.id
    session['role'] = user.role
    session['name'] = user.name

    return jsonify({'message': 'Login successful', 'user': user.to_dict()}), 200


@app.route('/api/auth/logout', methods=['POST'])
def logout():
    session.clear()
    return jsonify({'message': 'Logged out successfully'}), 200


@app.route('/api/auth/me', methods=['GET'])
def me():
    if 'user_id' not in session:
        return jsonify({'authenticated': False}), 200
    user = User.query.get(session['user_id'])
    if not user:
        session.clear()
        return jsonify({'authenticated': False}), 200
    return jsonify({'authenticated': True, 'user': user.to_dict()}), 200


# ---------------------------------------------------------------------------
# Category API
# ---------------------------------------------------------------------------

@app.route('/api/categories', methods=['GET'])
def get_categories():
    categories = Category.query.all()
    return jsonify([c.to_dict() for c in categories])


@app.route('/api/categories', methods=['POST'])
@role_required('admin', 'employee')
def create_category():
    data = request.get_json()
    category = Category(name=data['name'], color=data.get('color', '#FF7A00'))
    db.session.add(category)
    db.session.commit()
    return jsonify(category.to_dict()), 201


@app.route('/api/categories/<int:cat_id>', methods=['PUT'])
@role_required('admin', 'employee')
def update_category(cat_id):
    category = Category.query.get_or_404(cat_id)
    data = request.get_json()
    category.name = data.get('name', category.name)
    category.color = data.get('color', category.color)
    db.session.commit()
    return jsonify(category.to_dict())


@app.route('/api/categories/<int:cat_id>', methods=['DELETE'])
@role_required('admin', 'employee')
def delete_category(cat_id):
    category = Category.query.get_or_404(cat_id)
    db.session.delete(category)
    db.session.commit()
    return jsonify({'message': 'Category deleted'})


# ---------------------------------------------------------------------------
# Product API
# ---------------------------------------------------------------------------

@app.route('/api/products', methods=['GET'])
def get_products():
    search = request.args.get('search', '').strip()
    category_id = request.args.get('category_id')
    query = Product.query
    if search:
        query = query.filter(Product.name.ilike(f'%{search}%'))
    if category_id:
        query = query.filter_by(category_id=category_id)
    products = query.all()
    return jsonify([p.to_dict() for p in products])


@app.route('/api/products/<int:prod_id>', methods=['GET'])
def get_product(prod_id):
    product = Product.query.get_or_404(prod_id)
    return jsonify(product.to_dict())


@app.route('/api/products', methods=['POST'])
@role_required('admin', 'employee')
def create_product():
    data = request.get_json()
    product = Product(
        name=data['name'],
        category_id=data.get('category_id'),
        price=float(data.get('price', 0)),
        unit=data.get('unit', 'pcs'),
        tax=float(data.get('tax', 5.0)),
        description=data.get('description', ''),
        image=data.get('image') or '/static/images/placeholder.svg',
        status=data.get('status', 'active')
    )
    db.session.add(product)
    db.session.commit()
    return jsonify(product.to_dict()), 201


@app.route('/api/products/<int:prod_id>', methods=['PUT'])
@role_required('admin', 'employee')
def update_product(prod_id):
    product = Product.query.get_or_404(prod_id)
    data = request.get_json()
    product.name = data.get('name', product.name)
    product.category_id = data.get('category_id', product.category_id)
    product.price = float(data.get('price', product.price))
    product.unit = data.get('unit', product.unit)
    product.tax = float(data.get('tax', product.tax))
    product.description = data.get('description', product.description)
    product.image = data.get('image', product.image)
    product.status = data.get('status', product.status)
    db.session.commit()
    return jsonify(product.to_dict())


@app.route('/api/products/<int:prod_id>', methods=['DELETE'])
@role_required('admin', 'employee')
def delete_product(prod_id):
    product = Product.query.get_or_404(prod_id)
    db.session.delete(product)
    db.session.commit()
    return jsonify({'message': 'Product deleted'})


# ---------------------------------------------------------------------------
# Floor & Table API
# ---------------------------------------------------------------------------

@app.route('/api/floors', methods=['GET'])
def get_floors():
    floors = Floor.query.all()
    result = []
    for f in floors:
        d = f.to_dict()
        d['tables'] = [t.to_dict() for t in f.tables]
        result.append(d)
    return jsonify(result)


@app.route('/api/floors', methods=['POST'])
@role_required('admin', 'employee')
def create_floor():
    data = request.get_json()
    floor = Floor(name=data['name'])
    db.session.add(floor)
    db.session.commit()
    return jsonify(floor.to_dict()), 201


@app.route('/api/floors/<int:floor_id>', methods=['PUT'])
@role_required('admin', 'employee')
def update_floor(floor_id):
    floor = Floor.query.get_or_404(floor_id)
    data = request.get_json()
    floor.name = data.get('name', floor.name)
    db.session.commit()
    return jsonify(floor.to_dict())


@app.route('/api/floors/<int:floor_id>', methods=['DELETE'])
@role_required('admin', 'employee')
def delete_floor(floor_id):
    floor = Floor.query.get_or_404(floor_id)
    if floor.tables:
        return jsonify({'error': 'Cannot delete a floor that still has tables. Remove or move its tables first.'}), 400
    db.session.delete(floor)
    db.session.commit()
    return jsonify({'message': 'Floor deleted'})


@app.route('/api/floors/<int:floor_id>/duplicate', methods=['POST'])
@role_required('admin', 'employee')
def duplicate_floor(floor_id):
    """Clones a floor plus every table on it onto a brand-new floor, so a whole
    seating layout can be replicated in one click instead of recreating each
    table by hand."""
    floor = Floor.query.get_or_404(floor_id)

    new_floor = Floor(name=f'{floor.name} (Copy)')
    db.session.add(new_floor)
    db.session.flush()

    next_number = (db.session.query(db.func.max(Table.number)).scalar() or 0) + 1
    for t in floor.tables:
        new_table = Table(
            number=next_number,
            floor_id=new_floor.id,
            seats=t.seats,
            status='available'
        )
        db.session.add(new_table)
        db.session.flush()
        new_table.qr_code = generate_qr_payload(request.host_url.rstrip('/') + f'/self-order/{new_table.id}')
        next_number += 1

    db.session.commit()
    result = new_floor.to_dict()
    result['tables'] = [t.to_dict() for t in new_floor.tables]
    return jsonify(result), 201


@app.route('/api/tables', methods=['GET'])
def get_tables():
    tables = Table.query.all()
    return jsonify([t.to_dict() for t in tables])


@app.route('/api/tables', methods=['POST'])
@role_required('admin', 'employee')
def create_table():
    data = request.get_json()
    table = Table(
        number=data['number'],
        floor_id=data.get('floor_id'),
        seats=data.get('seats', 4),
        status=data.get('status', 'available')
    )
    db.session.add(table)
    db.session.commit()
    table.qr_code = generate_qr_payload(request.host_url.rstrip('/') + f'/self-order/{table.id}')
    db.session.commit()
    return jsonify(table.to_dict()), 201


@app.route('/api/tables/<int:table_id>', methods=['PUT'])
@role_required('admin', 'employee')
def update_table(table_id):
    table = Table.query.get_or_404(table_id)
    data = request.get_json()
    table.number = data.get('number', table.number)
    table.floor_id = data.get('floor_id', table.floor_id)
    table.seats = data.get('seats', table.seats)
    table.status = data.get('status', table.status)
    db.session.commit()
    return jsonify(table.to_dict())


@app.route('/api/tables/<int:table_id>', methods=['DELETE'])
@role_required('admin', 'employee')
def delete_table(table_id):
    table = Table.query.get_or_404(table_id)
    db.session.delete(table)
    db.session.commit()
    return jsonify({'message': 'Table deleted'})


@app.route('/api/tables/<int:table_id>/duplicate', methods=['POST'])
@role_required('admin', 'employee')
def duplicate_table(table_id):
    """Creates a copy of an existing table (same floor & seat count) with the
    next available table number, complete with its own fresh QR code."""
    table = Table.query.get_or_404(table_id)
    next_number = (db.session.query(db.func.max(Table.number)).scalar() or 0) + 1
    new_table = Table(
        number=next_number,
        floor_id=table.floor_id,
        seats=table.seats,
        status='available'
    )
    db.session.add(new_table)
    db.session.commit()
    new_table.qr_code = generate_qr_payload(request.host_url.rstrip('/') + f'/self-order/{new_table.id}')
    db.session.commit()
    return jsonify(new_table.to_dict()), 201


# ---------------------------------------------------------------------------
# Customer API
# ---------------------------------------------------------------------------

@app.route('/api/customers', methods=['GET'])
@login_required
def get_customers():
    search = request.args.get('search', '').strip()
    query = Customer.query
    if search:
        query = query.filter(
            (Customer.name.ilike(f'%{search}%')) |
            (Customer.phone.ilike(f'%{search}%')) |
            (Customer.email.ilike(f'%{search}%'))
        )
    customers = query.all()
    return jsonify([c.to_dict() for c in customers])


@app.route('/api/customers', methods=['POST'])
@login_required
def create_customer():
    data = request.get_json()
    customer = Customer(
        name=data['name'], email=data.get('email'),
        phone=data.get('phone'), address=data.get('address')
    )
    db.session.add(customer)
    db.session.commit()
    return jsonify(customer.to_dict()), 201


@app.route('/api/customers/<int:cust_id>', methods=['PUT'])
@login_required
def update_customer(cust_id):
    customer = Customer.query.get_or_404(cust_id)
    data = request.get_json()
    customer.name = data.get('name', customer.name)
    customer.email = data.get('email', customer.email)
    customer.phone = data.get('phone', customer.phone)
    customer.address = data.get('address', customer.address)
    db.session.commit()
    return jsonify(customer.to_dict())


@app.route('/api/customers/<int:cust_id>', methods=['DELETE'])
@login_required
def delete_customer(cust_id):
    customer = Customer.query.get_or_404(cust_id)
    db.session.delete(customer)
    db.session.commit()
    return jsonify({'message': 'Customer deleted'})


# ---------------------------------------------------------------------------
# Customer Dashboard API (self-service, role = customer)
# ---------------------------------------------------------------------------

@app.route('/api/customer/me', methods=['GET'])
@role_required('customer')
def customer_me():
    user = User.query.get(session['user_id'])
    customer = get_or_create_customer_for_user(user)
    db.session.commit()

    orders = Order.query.filter_by(customer_id=customer.id).order_by(Order.created_at.desc()).all()
    total_orders = len(orders)
    total_spent = sum(o.grand_total for o in orders if o.payment_status == 'paid')
    pending_orders = len([o for o in orders if o.status != 'completed'])

    return jsonify({
        'user': user.to_dict(),
        'customer': customer.to_dict(),
        'stats': {
            'total_orders': total_orders,
            'total_spent': round(total_spent, 2),
            'pending_orders': pending_orders,
            'loyalty_points': customer.loyalty_points,
            'points_value': points_value(customer.loyalty_points)
        },
        'recent_orders': [o.to_dict() for o in orders[:5]]
    })


@app.route('/api/customer/orders', methods=['GET'])
@role_required('customer')
def customer_orders():
    user = User.query.get(session['user_id'])
    customer = get_or_create_customer_for_user(user)
    db.session.commit()
    orders = Order.query.filter_by(customer_id=customer.id).order_by(Order.created_at.desc()).all()
    return jsonify([o.to_dict() for o in orders])


@app.route('/api/customer/points', methods=['GET'])
@role_required('customer')
def customer_points():
    """Loyalty points balance + history for the logged-in customer. Powers the
    'My Points' panel in the customer dashboard."""
    user = User.query.get(session['user_id'])
    customer = get_or_create_customer_for_user(user)
    db.session.commit()

    ledger = PointsLedger.query.filter_by(customer_id=customer.id) \
        .order_by(PointsLedger.created_at.desc()).limit(50).all()

    return jsonify({
        'loyalty_points': customer.loyalty_points,
        'points_value': points_value(customer.loyalty_points),
        'earn_rate': f'1 point for every ₹{POINTS_EARN_RATE:.0f} spent',
        'redeem_value': f'1 point = ₹{POINTS_REDEEM_VALUE:.0f} discount',
        'history': [l.to_dict() for l in ledger]
    })


# ---------------------------------------------------------------------------
# Coupon API
# ---------------------------------------------------------------------------

@app.route('/api/coupons', methods=['GET'])
def get_coupons():
    coupons = Coupon.query.all()
    return jsonify([c.to_dict() for c in coupons])


@app.route('/api/coupons', methods=['POST'])
@role_required('admin', 'employee')
def create_coupon():
    data = request.get_json()
    now = datetime.utcnow()
    coupon = Coupon(
        code=data['code'].upper(),
        discount_type=data.get('discount_type', 'percentage'),
        discount_value=float(data.get('discount_value', 0)),
        active=data.get('active', True),
        created_at=now,
        # Every coupon is valid for 5 days from the moment it's created.
        expiry_date=now + timedelta(days=COUPON_VALIDITY_DAYS)
    )
    db.session.add(coupon)
    db.session.commit()
    return jsonify(coupon.to_dict()), 201


@app.route('/api/coupons/validate/<code>', methods=['GET'])
def validate_coupon(code):
    coupon = Coupon.query.filter_by(code=code.upper(), active=True).first()
    if not coupon:
        return jsonify({'valid': False, 'error': 'Invalid or expired coupon'}), 404
    if coupon.is_expired():
        expired_on = coupon.expiry_date.strftime('%d %b %Y')
        return jsonify({'valid': False, 'error': f'This coupon expired on {expired_on}'}), 404
    return jsonify({'valid': True, 'coupon': coupon.to_dict()})


# ---------------------------------------------------------------------------
# Order API
# ---------------------------------------------------------------------------

@app.route('/api/orders', methods=['GET'])
def get_orders():
    status = request.args.get('status')
    order_type = request.args.get('order_type')
    query = Order.query
    if status:
        query = query.filter_by(status=status)
    if order_type:
        query = query.filter_by(order_type=order_type)
    orders = query.order_by(Order.created_at.desc()).all()
    return jsonify([o.to_dict() for o in orders])


@app.route('/api/orders/<int:order_id>', methods=['GET'])
def get_order(order_id):
    order = Order.query.get_or_404(order_id)
    return jsonify(order.to_dict())


@app.route('/api/orders', methods=['POST'])
def create_order():
    data = request.get_json()
    items_data = data.get('items', [])
    if not items_data:
        return jsonify({'error': 'Order must contain at least one item'}), 400

    order_type = data.get('order_type', 'pos')
    # Choosing a table is compulsory for orders placed from the POS cart.
    if order_type == 'pos' and not data.get('table_id'):
        return jsonify({'error': 'Please select a table before sending the order'}), 400

    customer_id = data.get('customer_id')
    if not customer_id and session.get('role') == 'customer' and 'user_id' in session:
        user = User.query.get(session['user_id'])
        if user:
            customer_id = get_or_create_customer_for_user(user).id

    order = Order(
        order_number=generate_order_number(),
        table_id=data.get('table_id'),
        customer_id=customer_id,
        order_type=order_type,
        status='to_cook',
        coupon_code=data.get('coupon_code')
    )
    db.session.add(order)
    db.session.flush()

    for item in items_data:
        product = Product.query.get(item['product_id'])
        if not product:
            continue
        qty = int(item.get('quantity', 1))
        order_item = OrderItem(
            order_id=order.id,
            product_id=product.id,
            product_name=product.name,
            quantity=qty,
            price=product.price,
            tax=product.tax,
            subtotal=round(product.price * qty, 2)
        )
        db.session.add(order_item)

    db.session.flush()
    db.session.refresh(order)

    discount_value = float(data.get('discount_value', 0))
    discount_type = data.get('discount_type', 'fixed')

    if order.coupon_code:
        coupon = Coupon.query.filter_by(code=order.coupon_code.upper(), active=True).first()
        if coupon and not coupon.is_expired():
            discount_value = coupon.discount_value
            discount_type = coupon.discount_type
        else:
            # Coupon is invalid or has passed its 5-day expiry — don't apply its discount.
            order.coupon_code = None

    recalc_order_totals(order, discount_value, discount_type)

    # Auto-apply the logged-in customer's loyalty points as an extra discount,
    # on top of any coupon, unless the client explicitly opts out.
    use_points = data.get('use_points', True)
    customer = Customer.query.get(customer_id) if customer_id else None
    if use_points and customer:
        apply_points_redemption(order, customer, data.get('points_to_redeem'))

    if order.table_id:
        table = Table.query.get(order.table_id)
        if table:
            table.status = 'occupied'

    db.session.commit()
    return jsonify(order.to_dict()), 201


@app.route('/api/orders/<int:order_id>/status', methods=['PUT'])
def update_order_status(order_id):
    order = Order.query.get_or_404(order_id)
    data = request.get_json()
    new_status = data.get('status')
    if new_status not in ('to_cook', 'preparing', 'completed'):
        return jsonify({'error': 'Invalid status'}), 400
    order.status = new_status
    db.session.commit()
    return jsonify(order.to_dict())


@app.route('/api/orders/<int:order_id>/pay', methods=['POST'])
def pay_order(order_id):
    order = Order.query.get_or_404(order_id)
    data = request.get_json()
    method = data.get('method', 'cash')

    if method not in ('cash', 'card', 'upi'):
        return jsonify({'error': 'Invalid payment method'}), 400

    payment = Payment(
        order_id=order.id,
        method=method,
        amount=order.grand_total,
        status='success',
        transaction_ref='TXN' + ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
    )
    db.session.add(payment)
    order.payment_status = 'paid'

    points_earned = 0
    if order.customer_id:
        customer = Customer.query.get(order.customer_id)
        points_earned = award_points_for_order(order, customer)

    if order.table_id:
        table = Table.query.get(order.table_id)
        if table:
            table.status = 'available'

    db.session.commit()

    response = {'order': order.to_dict(), 'payment': payment.to_dict(), 'points_earned': points_earned}
    if method == 'upi':
        upi_string = f"upi://pay?pa=odoocafe@upi&pn=OdooCafePOS&am={order.grand_total}&cu=INR&tn={order.order_number}"
        response['upi_qr'] = generate_qr_payload(upi_string)
    return jsonify(response), 200


# ---------------------------------------------------------------------------
# Reports API
# ---------------------------------------------------------------------------

@app.route('/api/reports/summary', methods=['GET'])
def reports_summary():
    orders = Order.query.filter_by(payment_status='paid').all()
    total_orders = len(orders)
    total_revenue = sum(o.grand_total for o in orders)
    avg_order_value = round(total_revenue / total_orders, 2) if total_orders else 0

    product_totals = {}
    category_totals = {}
    for order in orders:
        for item in order.items:
            product_totals[item.product_name] = product_totals.get(item.product_name, 0) + item.quantity
            product = Product.query.get(item.product_id)
            if product and product.category:
                cname = product.category.name
                category_totals[cname] = category_totals.get(cname, 0) + item.subtotal

    top_products = sorted(product_totals.items(), key=lambda x: x[1], reverse=True)[:5]
    top_categories = sorted(category_totals.items(), key=lambda x: x[1], reverse=True)[:5]

    monthly_sales = {}
    for order in orders:
        month_key = order.created_at.strftime('%Y-%m')
        monthly_sales[month_key] = monthly_sales.get(month_key, 0) + order.grand_total
    monthly_sales_sorted = sorted(monthly_sales.items())

    return jsonify({
        'total_orders': total_orders,
        'total_revenue': round(total_revenue, 2),
        'avg_order_value': avg_order_value,
        'top_products': [{'name': k, 'quantity': v} for k, v in top_products],
        'top_categories': [{'name': k, 'revenue': round(v, 2)} for k, v in top_categories],
        'monthly_sales': [{'month': k, 'revenue': round(v, 2)} for k, v in monthly_sales_sorted]
    })


# ---------------------------------------------------------------------------
# Database Seeding
# ---------------------------------------------------------------------------

def seed_database():
    """Populates the database with sample data if empty."""
    if User.query.first():
        return  # Already seeded

    # Users
    admin = User(name='Admin User', email='admin@odoocafe.com', role='admin')
    admin.set_password('admin123')
    employee = User(name='John Waiter', email='employee@odoocafe.com', role='employee')
    employee.set_password('employee123')
    customer_user = User(name='Demo Customer', email='customer@odoocafe.com', role='customer')
    customer_user.set_password('customer123')
    db.session.add_all([admin, employee, customer_user])

    # Categories
    cat_beverages = Category(name='Beverages', color='#3B82F6')
    cat_snacks = Category(name='Snacks', color='#F59E0B')
    cat_desserts = Category(name='Desserts', color='#EC4899')
    cat_main = Category(name='Main Course', color='#10B981')
    db.session.add_all([cat_beverages, cat_snacks, cat_desserts, cat_main])
    db.session.flush()

    # Products
    products = [
        Product(name='Cappuccino', category_id=cat_beverages.id, price=180, unit='cup', tax=5,
                description='Rich espresso topped with steamed milk foam', status='active'),
        Product(name='Cold Coffee', category_id=cat_beverages.id, price=160, unit='glass', tax=5,
                description='Chilled coffee blended with ice cream', status='active'),
        Product(name='Masala Chai', category_id=cat_beverages.id, price=60, unit='cup', tax=5,
                description='Traditional spiced Indian tea', status='active'),
        Product(name='Fresh Lime Soda', category_id=cat_beverages.id, price=90, unit='glass', tax=5,
                description='Refreshing lime soda', status='active'),
        Product(name='French Fries', category_id=cat_snacks.id, price=150, unit='plate', tax=5,
                description='Crispy golden fries with seasoning', status='active'),
        Product(name='Veg Spring Rolls', category_id=cat_snacks.id, price=200, unit='plate', tax=5,
                description='Crunchy rolls stuffed with vegetables', status='active'),
        Product(name='Paneer Tikka', category_id=cat_snacks.id, price=240, unit='plate', tax=5,
                description='Grilled cottage cheese skewers', status='active'),
        Product(name='Nachos Supreme', category_id=cat_snacks.id, price=220, unit='plate', tax=5,
                description='Loaded nachos with cheese and salsa', status='active'),
        Product(name='Chocolate Brownie', category_id=cat_desserts.id, price=140, unit='piece', tax=5,
                description='Warm fudgy brownie with chocolate sauce', status='active'),
        Product(name='Vanilla Ice Cream', category_id=cat_desserts.id, price=100, unit='scoop', tax=5,
                description='Classic vanilla ice cream', status='active'),
        Product(name='Cheesecake', category_id=cat_desserts.id, price=180, unit='slice', tax=5,
                description='Creamy New York style cheesecake', status='active'),
        Product(name='Margherita Pizza', category_id=cat_main.id, price=320, unit='plate', tax=12,
                description='Classic pizza with tomato and mozzarella', status='active'),
        Product(name='Veg Biryani', category_id=cat_main.id, price=280, unit='plate', tax=12,
                description='Fragrant rice cooked with mixed vegetables', status='active'),
        Product(name='Pasta Alfredo', category_id=cat_main.id, price=300, unit='plate', tax=12,
                description='Creamy white sauce pasta', status='active'),
        Product(name='Grilled Sandwich', category_id=cat_main.id, price=180, unit='plate', tax=5,
                description='Toasted sandwich with cheese and veggies', status='active'),
    ]
    db.session.add_all(products)

    # Floors & Tables
    ground = Floor(name='Ground Floor')
    first = Floor(name='First Floor')
    db.session.add_all([ground, first])
    db.session.flush()

    tables = [
        Table(number=1, floor_id=ground.id, seats=4, status='available'),
        Table(number=2, floor_id=ground.id, seats=2, status='occupied'),
        Table(number=3, floor_id=ground.id, seats=6, status='available'),
        Table(number=4, floor_id=first.id, seats=4, status='available'),
        Table(number=5, floor_id=first.id, seats=4, status='occupied'),
    ]
    db.session.add_all(tables)
    db.session.flush()

    for t in tables:
        t.qr_code = generate_qr_payload(f'http://localhost:5000/self-order/{t.id}')

    # Customers
    customers = [
        Customer(name='Rahul Sharma', email='rahul@example.com', phone='9876543210', address='Coimbatore, TN'),
        Customer(name='Priya Patel', email='priya@example.com', phone='9876543211', address='Chennai, TN'),
        Customer(name='Amit Kumar', email='amit@example.com', phone='9876543212', address='Bangalore, KA'),
    ]
    db.session.add_all(customers)

    # Coupons (each valid for 5 days from creation, per COUPON_VALIDITY_DAYS)
    coupon_now = datetime.utcnow()
    coupons = [
        Coupon(code='WELCOME10', discount_type='percentage', discount_value=10, active=True,
               created_at=coupon_now, expiry_date=coupon_now + timedelta(days=COUPON_VALIDITY_DAYS)),
        Coupon(code='FLAT50', discount_type='fixed', discount_value=50, active=True,
               created_at=coupon_now, expiry_date=coupon_now + timedelta(days=COUPON_VALIDITY_DAYS)),
        Coupon(code='FESTIVE20', discount_type='percentage', discount_value=20, active=True,
               created_at=coupon_now, expiry_date=coupon_now + timedelta(days=COUPON_VALIDITY_DAYS)),
    ]
    db.session.add_all(coupons)

    # Promotions
    promotions = [
        Promotion(title='Happy Hours', description='20% off on all beverages 3-6 PM', active=True),
        Promotion(title='Weekend Special', description='Buy 1 Get 1 on Desserts', active=True),
    ]
    db.session.add_all(promotions)

    db.session.commit()

    # Sample historical orders for reports
    import datetime as dt
    all_products = Product.query.all()
    for i in range(25):
        days_ago = random.randint(0, 60)
        order_date = datetime.utcnow() - timedelta(days=days_ago)
        order = Order(
            order_number=generate_order_number() + f'-{i}',
            order_type=random.choice(['pos', 'self_order']),
            status='completed',
            payment_status='paid',
            created_at=order_date
        )
        db.session.add(order)
        db.session.flush()

        chosen = random.sample(all_products, k=random.randint(1, 4))
        for p in chosen:
            qty = random.randint(1, 3)
            db.session.add(OrderItem(
                order_id=order.id, product_id=p.id, product_name=p.name,
                quantity=qty, price=p.price, tax=p.tax,
                subtotal=round(p.price * qty, 2)
            ))
        db.session.flush()
        db.session.refresh(order)
        recalc_order_totals(order, 0, 'fixed')
        db.session.add(Payment(
            order_id=order.id, method=random.choice(['cash', 'card', 'upi']),
            amount=order.grand_total, status='success',
            transaction_ref='TXN' + ''.join(random.choices(string.ascii_uppercase + string.digits, k=10)),
            created_at=order_date
        ))

    db.session.commit()
    print('✅ Database seeded with sample data.')


@app.cli.command('seed')
def seed_command():
    """CLI command: flask seed"""
    seed_database()


# ---------------------------------------------------------------------------
# App Entrypoint
# ---------------------------------------------------------------------------

with app.app_context():
    db.create_all()
    seed_database()

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
